# Generated by Django 2.2 on 2019-04-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=100)),
                ('shorted_url', models.CharField(blank=True, max_length=100)),
                ('original_url', models.URLField()),
            ],
        ),
    ]
